[phases.setup]
# On ajoute explicitement composer à la liste des paquets Nix
nixPkgs = ['php82', 'php82Extensions.mbstring', 'php82Extensions.iconv', 'php82Extensions.gd', 'php82Packages.composer']
cmds = [
    'mkdir -p /usr/local/etc/php/conf.d',
    'echo "upload_max_filesize=40M" > /usr/local/etc/php/conf.d/z-custom.ini',
    'echo "post_max_size=45M" >> /usr/local/etc/php/conf.d/z-custom.ini'
]

[start]
cmd = "php -d upload_max_filesize=40M -d post_max_size=45M artisan serve --host=0.0.0.0 --port=80"
