import zipfile
import io

# Liste des migrations (nom du fichier et contenu)
migrations = {
    "2024_01_01_000000_create_cache_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('cache', function (Blueprint $table) {\n            $table->string('key', 255)->primary();\n            $table->mediumText('value');\n            $table->integer('expiration');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('cache');\n    }\n};""",
    
    "2024_01_01_000001_create_cache_locks_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('cache_locks', function (Blueprint $table) {\n            $table->string('key', 255)->primary();\n            $table->string('owner', 255);\n            $table->integer('expiration');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('cache_locks');\n    }\n};""",
    
    "2024_01_01_000002_create_sites_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('sites', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('nom_site', 100);\n            $table->string('code_site', 255)->nullable();\n            $table->string('type_site', 50);\n            $table->string('region', 50)->nullable();\n            $table->time('heures_ouverture')->nullable();\n            $table->time('heures_fermeture')->nullable();\n            $table->integer('statut')->default(1);\n            $table->timestamps();\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('sites');\n    }\n};""",
    
    "2024_01_01_000003_create_roles_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('roles', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('nom_role', 100);\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('roles');\n    }\n};""",
    
    "2024_01_01_000004_create_users_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('users', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('nom', 100);\n            $table->string('prenom', 255);\n            $table->string('email', 255)->unique();\n            $table->string('password', 255);\n            $table->unsignedBigInteger('id_role')->nullable();\n            $table->unsignedBigInteger('id_site')->nullable();\n            $table->integer('statut')->default(1);\n            $table->timestamps();\n\n            $table->foreign('id_role')->references('id')->on('roles')->onDelete('set null');\n            $table->foreign('id_site')->references('id')->on('sites')->onDelete('set null');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('users');\n    }\n};""",
    
    "2024_01_01_000005_create_user_role_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('user_role', function (Blueprint $table) {\n            $table->unsignedBigInteger('id_user');\n            $table->unsignedBigInteger('id_role');\n\n            $table->foreign('id_user')->references('id')->on('users')->onDelete('cascade');\n            $table->foreign('id_role')->references('id')->on('roles')->onDelete('cascade');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('user_role');\n    }\n};""",
    
    "2024_01_01_000006_create_caisses_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('caisses', function (Blueprint $table) {\n            $table->increments('id');\n            $table->string('code', 50)->unique();\n            $table->string('libelle', 100);\n            $table->unsignedBigInteger('site_id');\n            $table->decimal('solde_initial', 10, 2)->default('0.00');\n            $table->tinyInteger('is_active')->default(1);\n            $table->timestamps();\n\n            $table->foreign('site_id')->references('id')->on('sites')->onDelete('cascade');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('caisses');\n    }\n};""",
    
    "2024_01_01_000007_create_caisse_ouvertures_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('caisse_ouvertures', function (Blueprint $table) {\n            $table->increments('id');\n            $table->unsignedBigInteger('user_id');\n            $table->unsignedInteger('caisse_id');\n            $table->dateTime('date_ouverture');\n            $table->dateTime('date_fermeture')->nullable();\n            $table->decimal('montant_ouverture', 10, 2)->nullable();\n            $table->decimal('montant_fermeture', 10, 2)->nullable();\n            $table->string('montant_saisie_caisse', 255)->nullable();\n            $table->enum('statut', ['ouvert', 'fermé'])->default('ouvert');\n            $table->integer('id_controlleur')->nullable();\n            $table->string('montant_controlleur', 255)->nullable();\n            $table->date('date_fermeture_controlleur')->nullable();\n            $table->timestamps();\n\n            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');\n            $table->foreign('caisse_id')->references('id')->on('caisses')->onDelete('cascade');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('caisse_ouvertures');\n    }\n};""",
    
    "2024_01_01_000008_create_chronos_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('chronos', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('service', 10)->nullable();\n            $table->char('year', 2)->nullable();\n            $table->char('month', 2)->nullable();\n            $table->integer('counter')->default(0);\n\n            $table->unique(['service', 'year', 'month']);\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('chronos');\n    }\n};""",
    
    "2024_01_01_000009_create_services_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('services', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('nom_service', 100)->unique();\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('services');\n    }\n};""",
    
    "2024_01_01_000010_create_type_services_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('type_services', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('nom_type_service', 100);\n            $table->string('montant', 255)->default('0');\n            $table->unsignedBigInteger('id_service')->nullable();\n            $table->timestamps();\n\n            $table->foreign('id_service')->references('id')->on('services')->onDelete('set null');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('type_services');\n    }\n};""",
    
    "2024_01_01_000011_create_entites_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('entites', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('nom', 255);\n            $table->integer('statut')->default(1);\n            $table->timestamps();\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('entites');\n    }\n};""",
    
    "2024_01_01_000012_create_detail_type_services_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('detail_type_services', function (Blueprint $table) {\n            $table->increments('id');\n            $table->unsignedInteger('id_type_services');\n            $table->unsignedInteger('id_service');\n            $table->unsignedInteger('id_site');\n            $table->unsignedInteger('id_entite')->nullable();\n            $table->string('element_facturation', 255);\n            $table->bigInteger('montant');\n            $table->integer('statut')->nullable()->comment('1: Activé; 2 : Désactivé');\n            $table->timestamps();\n\n            $table->foreign('id_type_services')->references('id')->on('type_services')->onDelete('cascade');\n            $table->foreign('id_service')->references('id')->on('services')->onDelete('cascade');\n            $table->foreign('id_site')->references('id')->on('sites')->onDelete('cascade');\n            $table->foreign('id_entite')->references('id')->on('entites')->onDelete('set null');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('detail_type_services');\n    }\n};""",
    
    "2024_01_01_000013_create_entreprises_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('entreprises', function (Blueprint $table) {\n            $table->increments('id');\n            $table->string('nom_entreprise', 255);\n            $table->string('nom_representant_legal', 255);\n            $table->string('prenom_representant_legal', 255)->nullable();\n            $table->string('date_de_naissance_representant_legal', 255)->nullable();\n            $table->string('profession_representant_legal', 255)->nullable();\n            $table->string('telephone_representant_legal', 20)->nullable();\n            $table->string('registre_commerce', 255);\n            $table->string('compte_contribuale', 255);\n            $table->string('prefecture', 255)->nullable();\n            $table->string('sous_prefecture', 255)->nullable();\n            $table->string('region', 255)->nullable();\n            $table->timestamps();\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('entreprises');\n    }\n};""",
    
    "2024_01_01_000014_create_clients_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('clients', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('nom', 100);\n            $table->string('prenom', 255);\n            $table->string('civilite', 255)->nullable();\n            $table->string('adresse', 255)->nullable();\n            $table->string('district_client', 255)->nullable();\n            $table->string('prefecture_client', 255)->nullable();\n            $table->string('sous_prefecture_client', 255)->nullable();\n            $table->string('telephone', 20)->nullable();\n            $table->string('password', 255);\n            $table->string('date_naissance', 255)->nullable();\n            $table->string('ville_naissance', 255)->nullable();\n            $table->string('email', 100)->nullable();\n            $table->integer('statut')->default(1);\n            $table->string('validite', 100)->nullable();\n            $table->unsignedInteger('entreprise_id')->nullable();\n            $table->timestamps();\n\n            $table->foreign('entreprise_id')->references('id')->on('entreprises')->onDelete('set null');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('clients');\n    }\n};""",
    
    "2024_01_01_000015_create_vehicules_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('vehicules', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('annee_production', 100)->nullable();\n            $table->string('vin', 50)->unique();\n            $table->string('marque', 50)->nullable();\n            $table->string('modele', 50)->nullable();\n            $table->string('couleur', 255)->nullable();\n            $table->string('source_energie', 255)->nullable();\n            $table->string('genre_vehicule', 255)->nullable();\n            $table->string('poids_total_charge', 255)->nullable();\n            $table->string('poids_utile', 255)->nullable();\n            $table->string('poids_vide', 255)->nullable();\n            $table->string('puissance_administrative', 255)->nullable();\n            $table->integer('places_assises')->nullable();\n            $table->integer('nombre_essieux')->nullable();\n            $table->string('date_mise_circulation', 255)->nullable();\n            $table->unsignedBigInteger('id_site')->nullable();\n            $table->string('num_immatriculation', 50)->nullable();\n            $table->string('num_immatriculation_precedant', 255)->nullable();\n            $table->date('date_immatriculation')->nullable();\n            $table->date('date_immatriculation_precedant')->nullable();\n            $table->string('nb_plaque', 100)->nullable();\n            $table->string('carrosserie', 100)->nullable();\n            $table->string('type_technique', 100)->nullable();\n            $table->string('controleur_technique', 255)->nullable();\n            $table->string('usage_vehicule', 100)->nullable();\n            $table->string('code_de_region', 225)->nullable();\n            $table->string('physique_morale', 225)->nullable();\n            $table->unsignedInteger('entreprise_id')->nullable();\n            $table->unsignedBigInteger('id_client')->nullable();\n            $table->unsignedInteger('model_id')->nullable();\n            $table->unsignedInteger('marque_id')->nullable();\n            $table->string('cylindree', 255)->nullable();\n            $table->string('gage', 20)->nullable();\n            $table->timestamps();\n\n            $table->foreign('id_site')->references('id')->on('sites')->onDelete('set null');\n            $table->foreign('id_client')->references('id')->on('clients')->onDelete('set null');\n            $table->foreign('entreprise_id')->references('id')->on('entreprises')->onDelete('set null');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('vehicules');\n    }\n};""",
    
    "2024_01_01_000016_create_dossiers_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('dossiers', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->unsignedBigInteger('id_vehicule')->nullable();\n            $table->unsignedBigInteger('id_user')->nullable();\n            $table->unsignedBigInteger('id_client')->nullable();\n            $table->unsignedBigInteger('id_service')->nullable();\n            $table->integer('id_type_service')->nullable();\n            $table->integer('id_site')->nullable();\n            $table->json('detail')->nullable();\n            $table->string('reserverNumero', 255)->nullable();\n            $table->string('numeroDiplomatique', 255)->nullable();\n            $table->integer('modification_log_id')->nullable();\n            $table->integer('statut')->default(1);\n            $table->integer('statut_paiement')->default(1);\n            $table->dateTime('date_paiement')->nullable();\n            $table->integer('paiement_validated_by')->nullable();\n            $table->integer('statut_numerisation')->default(1);\n            $table->text('motif_rejet')->nullable();\n            $table->integer('dossier_rejeted_by')->nullable();\n            $table->dateTime('date_rejet')->nullable();\n            $table->string('num_chrono', 255)->nullable();\n            $table->string('date_creation', 255)->nullable();\n            $table->string('date_validation', 255)->nullable();\n            $table->integer('status_pose_plaque')->nullable();\n            $table->integer('id_dossier_lier')->nullable();\n            $table->timestamps();\n\n            $table->foreign('id_vehicule')->references('id')->on('vehicules')->onDelete('set null');\n            $table->foreign('id_user')->references('id')->on('users')->onDelete('set null');\n            $table->foreign('id_client')->references('id')->on('clients')->onDelete('set null');\n            $table->foreign('id_service')->references('id')->on('services')->onDelete('set null');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('dossiers');\n    }\n};""",
    
    "2024_01_01_000017_create_dossier_services_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('dossier_services', function (Blueprint $table) {\n            $table->unsignedBigInteger('id_dossier');\n            $table->unsignedBigInteger('id_service');\n\n            $table->foreign('id_dossier')->references('id')->on('dossiers')->onDelete('cascade');\n            $table->foreign('id_service')->references('id')->on('services')->onDelete('cascade');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('dossier_services');\n    }\n};""",
    
    "2024_01_01_000018_create_documents_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('documents', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->unsignedBigInteger('id_dossier')->nullable();\n            $table->string('formulaire_recensement', 255)->nullable();\n            $table->string('fiche_rti', 255)->nullable();\n            $table->string('fiche_civio', 255)->nullable();\n            $table->string('cni', 255)->nullable();\n            $table->string('carte_professionnelle', 255)->nullable();\n            $table->string('permis_conduire', 255)->nullable();\n            $table->string('documents_douane', 255)->nullable();\n            $table->string('fiche_demande_carte_grise', 255)->nullable();\n            $table->string('assurance', 255)->nullable();\n            $table->timestamps();\n\n            $table->foreign('id_dossier')->references('id')->on('dossiers')->onDelete('set null');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('documents');\n    }\n};""",
    
    "2024_01_01_000019_create_paiements_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('paiements', function (Blueprint $table) {\n            $table->increments('id');\n            $table->integer('id_dossier');\n            $table->unsignedInteger('caisse_ouverture_id');\n            $table->unsignedBigInteger('user_id');\n            $table->integer('id_site')->nullable();\n            $table->integer('caisse_id')->nullable();\n            $table->integer('id_service')->nullable();\n            $table->integer('id_vehicule')->nullable();\n            $table->string('reference', 50);\n            $table->decimal('montant', 10, 2);\n            $table->string('mode_paiement', 100);\n            $table->json('description')->nullable();\n            $table->timestamps();\n\n            $table->foreign('caisse_ouverture_id')->references('id')->on('caisse_ouvertures')->onDelete('cascade');\n            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('paiements');\n    }\n};""",
    
    "2024_01_01_000020_create_transactions_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('transactions', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->unsignedBigInteger('id_dossier')->nullable();\n            $table->string('Montant', 255);\n            $table->dateTime('date_transaction')->default(DB::raw('CURRENT_TIMESTAMP'));\n            $table->string('type_transaction', 50);\n            $table->unsignedBigInteger('id_user')->nullable();\n            $table->integer('statut')->default(1);\n            $table->timestamps();\n\n            $table->foreign('id_dossier')->references('id')->on('dossiers')->onDelete('set null');\n            $table->foreign('id_user')->references('id')->on('users')->onDelete('set null');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('transactions');\n    }\n};""",
    
    "2024_01_01_000021_create_recus_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('recus', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->unsignedBigInteger('id_transaction')->nullable();\n            $table->dateTime('date_emission')->default(DB::raw('CURRENT_TIMESTAMP'));\n            $table->string('Format', 50);\n            $table->timestamps();\n\n            $table->foreign('id_transaction')->references('id')->on('transactions')->onDelete('set null');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('recus');\n    }\n};""",
    
    "2024_01_01_000022_create_controlleur_caisses_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('controlleur_caisses', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->decimal('montant_caisse', 15, 2)->nullable();\n            $table->decimal('montant_controlleur', 15, 2)->nullable();\n            $table->tinyInteger('status')->default(1);\n            $table->tinyInteger('status_raf')->default(0);\n            $table->unsignedBigInteger('caisse_id')->nullable();\n            $table->string('code_caisse', 50)->nullable();\n            $table->unsignedBigInteger('id_site')->nullable();\n            $table->timestamp('date_fermeture_controlleur')->nullable();\n            $table->timestamp('date_ouverture_raf')->nullable();\n            $table->timestamp('date_fermeture_raf')->nullable();\n            $table->timestamp('date_ouverture_controlleur')->nullable();\n            $table->date('date')->nullable();\n            $table->timestamps();\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('controlleur_caisses');\n    }\n};""",
    
    "2024_01_01_000023_create_corrections_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('corrections', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->unsignedBigInteger('dossier_id');\n            $table->unsignedBigInteger('user_id');\n            $table->unsignedBigInteger('site_id')->nullable();\n            $table->string('origine', 50);\n            $table->integer('status')->nullable();\n            $table->longText('corrections');\n            $table->text('message')->nullable();\n            $table->timestamps();\n\n            $table->foreign('dossier_id')->references('id')->on('dossiers')->onDelete('cascade');\n            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');\n            $table->foreign('site_id')->references('id')->on('sites')->onDelete('set null');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('corrections');\n    }\n};""",
    
    "2024_01_01_000024_create_rejets_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('rejets', function (Blueprint $table) {\n            $table->increments('id');\n            $table->string('motif', 255);\n            $table->string('service_id', 100);\n            $table->string('id_type_services', 100);\n            $table->timestamps();\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('rejets');\n    }\n};""",
    
    "2024_01_01_000025_create_genre_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('genre', function (Blueprint $table) {\n            $table->increments('id');\n            $table->string('nom', 100);\n            $table->integer('nb_plaque');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('genre');\n    }\n};""",
    
    "2024_01_01_000026_create_marque_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('marque', function (Blueprint $table) {\n            $table->increments('id');\n            $table->string('nom', 100)->unique();\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('marque');\n    }\n};""",
    
    "2024_01_01_000027_create_model_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('model', function (Blueprint $table) {\n            $table->increments('id');\n            $table->string('nom', 100);\n            $table->unsignedInteger('marque_id');\n            $table->timestamps();\n\n            $table->foreign('marque_id')->references('id')->on('marque')->onDelete('cascade');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('model');\n    }\n};""",
    
    "2024_01_01_000028_create_type_personne_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('type_personne', function (Blueprint $table) {\n            $table->increments('id');\n            $table->string('nom', 100);\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('type_personne');\n    }\n};""",
    
    "2024_01_01_000029_create_permissions_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('permissions', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('Nom_Permission', 50);\n            $table->unsignedInteger('service_id');\n            $table->unsignedInteger('type_service_id');\n            $table->timestamps();\n\n            $table->foreign('service_id')->references('id')->on('services')->onDelete('cascade');\n            $table->foreign('type_service_id')->references('id')->on('type_services')->onDelete('cascade');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('permissions');\n    }\n};""",
    
    "2024_01_01_000030_create_user_permission_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('user_permission', function (Blueprint $table) {\n            $table->unsignedBigInteger('id_user');\n            $table->unsignedBigInteger('id_Permission');\n\n            $table->foreign('id_user')->references('id')->on('users')->onDelete('cascade');\n            $table->foreign('id_Permission')->references('id')->on('permissions')->onDelete('cascade');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('user_permission');\n    }\n};""",
    
    "2024_01_01_000031_create_modification_logs_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('modification_logs', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->unsignedBigInteger('user_id');\n            $table->string('model_type', 255);\n            $table->unsignedBigInteger('model_id')->nullable();\n            $table->json('old_values')->nullable();\n            $table->json('new_values')->nullable();\n            $table->timestamps();\n\n            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('modification_logs');\n    }\n};""",
    
    "2024_01_01_000032_create_sessions_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('sessions', function (Blueprint $table) {\n            $table->string('id', 255)->primary();\n            $table->unsignedBigInteger('user_id')->nullable();\n            $table->string('ip_address', 45)->nullable();\n            $table->text('user_agent')->nullable();\n            $table->longText('payload');\n            $table->integer('last_activity');\n\n            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');\n            $table->index('last_activity');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('sessions');\n    }\n};""",
    
    "2024_01_01_000033_create_jobs_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('jobs', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('queue', 255);\n            $table->longText('payload');\n            $table->tinyInteger('attempts')->unsigned();\n            $table->unsignedInteger('reserved_at')->nullable();\n            $table->unsignedInteger('available_at');\n            $table->unsignedInteger('created_at');\n            $table->index('queue');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('jobs');\n    }\n};""",
    
    "2024_01_01_000034_create_job_batches_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('job_batches', function (Blueprint $table) {\n            $table->string('id', 255)->primary();\n            $table->string('name', 255);\n            $table->integer('total_jobs');\n            $table->integer('pending_jobs');\n            $table->integer('failed_jobs');\n            $table->longText('failed_job_ids');\n            $table->mediumText('options')->nullable();\n            $table->integer('cancelled_at')->nullable();\n            $table->integer('created_at');\n            $table->integer('finished_at')->nullable();\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('job_batches');\n    }\n};""",
    
    "2024_01_01_000035_create_failed_jobs_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('failed_jobs', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('uuid', 255)->unique();\n            $table->text('connection');\n            $table->text('queue');\n            $table->longText('payload');\n            $table->longText('exception');\n            $table->timestamp('failed_at')->useCurrent();\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('failed_jobs');\n    }\n};""",
    
    "2024_01_01_000036_create_migrations_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('migrations', function (Blueprint $table) {\n            $table->increments('id');\n            $table->string('migration', 255);\n            $table->integer('batch');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('migrations');\n    }\n};""",
    
    "2024_01_01_000037_create_personal_access_tokens_table.php": """<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;\nuse Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\Schema;\n\nreturn new class extends Migration\n{\n    public function up()\n    {\n        Schema::create('personal_access_tokens', function (Blueprint $table) {\n            $table->bigIncrements('id');\n            $table->string('tokenable_type', 255);\n            $table->unsignedBigInteger('tokenable_id');\n            $table->text('name');\n            $table->string('token', 64)->unique();\n            $table->text('abilities')->nullable();\n            $table->timestamp('last_used_at')->nullable();\n            $table->timestamp('expires_at')->nullable();\n            $table->timestamps();\n\n            $table->index(['tokenable_type', 'tokenable_id']);\n            $table->index('expires_at');\n        });\n    }\n\n    public function down()\n    {\n        Schema::dropIfExists('personal_access_tokens');\n    }\n};"""
}

# Création d'un fichier zip en mémoire
zip_buffer = io.BytesIO()
with zipfile.ZipFile(zip_buffer, 'a', zipfile.ZIP_DEFLATED, False) as zip_file:
    for filename, content in migrations.items():
        zip_file.writestr(filename, content)

# Sauvegarde du fichier zip
zip_path = 'migrations.zip'
with open(zip_path, 'wb') as f:
    f.write(zip_buffer.getvalue())

zip_path