<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CountryController extends Controller
{
    //

    public function index()
    {
        $countries = [
            ["keyname" => "BR", "textvalue" => "Brésil"],
            ["keyname" => "BF", "textvalue" => "Burkina Faso"],
            ["keyname" => "LS", "textvalue" => "Lesotho"],
            ["keyname" => "PT", "textvalue" => "Portugal"],
            ["keyname" => "NP", "textvalue" => "Népal"],
            ["keyname" => "HT", "textvalue" => "Haïti"],
            ["keyname" => "EG", "textvalue" => "Égypte"],
            ["keyname" => "PF", "textvalue" => "Polynésie française"],
            ["keyname" => "AL", "textvalue" => "Albanie"],
            ["keyname" => "AF", "textvalue" => "Afghanistan"],
            ["keyname" => "GA", "textvalue" => "Gabon"],
            ["keyname" => "KN", "textvalue" => "Saint-Kitts-et-Nevis"],
            ["keyname" => "UG", "textvalue" => "Ouganda"],
            ["keyname" => "VN", "textvalue" => "Viêt Nam"],
            ["keyname" => "HK", "textvalue" => "Hong Kong"],
            ["keyname" => "BT", "textvalue" => "Bhoutan"],
            ["keyname" => "DO", "textvalue" => "République dominicaine"],
            ["keyname" => "NO", "textvalue" => "Norvège"],
            ["keyname" => "TL", "textvalue" => "Timor-Leste"],
            ["keyname" => "LT", "textvalue" => "Lituanie"],
            ["keyname" => "AR", "textvalue" => "Argentine"],
            ["keyname" => "SA", "textvalue" => "Arabie Saoudite"],
            ["keyname" => "LI", "textvalue" => "Liechtenstein"],
            ["keyname" => "DZ", "textvalue" => "Algérie"],
            ["keyname" => "ML", "textvalue" => "Mali"],
            ["keyname" => "IE", "textvalue" => "Irlande"],
            ["keyname" => "DM", "textvalue" => "Dominique"],
            ["keyname" => "CV", "textvalue" => "Cap-Vert"],
            ["keyname" => "NG", "textvalue" => "Nigeria"],
            ["keyname" => "NI", "textvalue" => "Nicaragua"],
            ["keyname" => "CZ", "textvalue" => "République tchèque"],
            ["keyname" => "BJ", "textvalue" => "Bénin"],
            ["keyname" => "IO", "textvalue" => "Territoire britannique de l’Océan Indien"],
            ["keyname" => "SI", "textvalue" => "Slovénie"],
            ["keyname" => "MW", "textvalue" => "Malawi"],
            ["keyname" => "BS", "textvalue" => "Bahamas"],
            ["keyname" => "SK", "textvalue" => "Slovaquie"],
            ["keyname" => "IR", "textvalue" => "Iran"],
            ["keyname" => "TG", "textvalue" => "Togo"],
            ["keyname" => "TO", "textvalue" => "Tonga"],
            ["keyname" => "MZ", "textvalue" => "Mozambique"],
            ["keyname" => "UM", "textvalue" => "Îles mineures éloignées des États-Unis"],
            ["keyname" => "SB", "textvalue" => "Îles Salomon"],
            ["keyname" => "ES", "textvalue" => "Espagne"],
            ["keyname" => "CU", "textvalue" => "Cuba"],
            ["keyname" => "LV", "textvalue" => "Lettonie"],
            ["keyname" => "GB", "textvalue" => "Royaume-Uni"],
            ["keyname" => "BG", "textvalue" => "Bulgarie"],
            ["keyname" => "PR", "textvalue" => "Puerto Rico"],
            ["keyname" => "KH", "textvalue" => "Cambodge"],
            ["keyname" => "PA", "textvalue" => "Panama"],
            ["keyname" => "TM", "textvalue" => "Turkménistan"],
            ["keyname" => "KI", "textvalue" => "Kiribati"],
            ["keyname" => "KW", "textvalue" => "Koweït"],
            ["keyname" => "SO", "textvalue" => "Somalie"],
            ["keyname" => "TW", "textvalue" => "Taiwan"],
            ["keyname" => "LU", "textvalue" => "Luxembourg"],
            ["keyname" => "SC", "textvalue" => "Seychelles"],
            ["keyname" => "PS", "textvalue" => "Palestine"],
            ["keyname" => "SV", "textvalue" => "Salvador"],
            ["keyname" => "CH", "textvalue" => "Suisse"],
            ["keyname" => "CL", "textvalue" => "Chili"],
            ["keyname" => "TF", "textvalue" => "Terres australes et antarctiques françaises"],
            ["keyname" => "SR", "textvalue" => "Suriname"],
            ["keyname" => "SY", "textvalue" => "Syrie"],
            ["keyname" => "SM", "textvalue" => "Saint-Marin"],
            ["keyname" => "CX", "textvalue" => "Île Christmas"],
            ["keyname" => "IT", "textvalue" => "Italie"],
            ["keyname" => "BN", "textvalue" => "Brunei Darussalam"],
            ["keyname" => "CY", "textvalue" => "Chypre"],
            ["keyname" => "TH", "textvalue" => "Thaïlande"],
            ["keyname" => "IS", "textvalue" => "Islande"],
            ["keyname" => "RO", "textvalue" => "Roumanie"],
            ["keyname" => "TD", "textvalue" => "Tchad"],
            ["keyname" => "GT", "textvalue" => "Guatemala"],
            ["keyname" => "AO", "textvalue" => "Angola"],
            ["keyname" => "MF", "textvalue" => "Saint-Martin (partie française)"],
            ["keyname" => "VU", "textvalue" => "Vanuatu"],
            ["keyname" => "SG", "textvalue" => "Singapour"],
            ["keyname" => "PK", "textvalue" => "Pakistan"],
            ["keyname" => "JO", "textvalue" => "Jordanie"],
            ["keyname" => "MK", "textvalue" => "Macédoine"],
            ["keyname" => "WS", "textvalue" => "Samoa"],
            ["keyname" => "BA", "textvalue" => "Bosnie-Herzégovine"],
            ["keyname" => "CR", "textvalue" => "Costa Rica"],
            ["keyname" => "SD", "textvalue" => "Soudan"],
            ["keyname" => "LC", "textvalue" => "Sainte-Lucie"],
            ["keyname" => "MP", "textvalue" => "Îles Mariannes du Nord"],
            ["keyname" => "MS", "textvalue" => "Montserrat"],
            ["keyname" => "MN", "textvalue" => "Mongolie"],
            ["keyname" => "CO", "textvalue" => "Colombie"],
            ["keyname" => "HM", "textvalue" => "Îles Heard-et-MacDonald"],
            ["keyname" => "SL", "textvalue" => "Sierra Leone"],
            ["keyname" => "EC", "textvalue" => "Équateur"],
            ["keyname" => "US", "textvalue" => "États-Unis"],
            ["keyname" => "NR", "textvalue" => "Nauru"],
            ["keyname" => "MM", "textvalue" => "Myanmar"],
            ["keyname" => "AG", "textvalue" => "Antigua-et-Barbuda"],
            ["keyname" => "AS", "textvalue" => "Samoa américaines"],
            ["keyname" => "PE", "textvalue" => "Pérou"],
            ["keyname" => "KG", "textvalue" => "Kirghizistan"],
            ["keyname" => "DJ", "textvalue" => "Djibouti"],
            ["keyname" => "TT", "textvalue" => "Trinité-et-Tobago"],
            ["keyname" => "GN", "textvalue" => "Guinée"],
            ["keyname" => "CK", "textvalue" => "Îles Cook"],
            ["keyname" => "HU", "textvalue" => "Hongrie"],
            ["keyname" => "ZA", "textvalue" => "Afrique du Sud"],
            ["keyname" => "JP", "textvalue" => "Japon"],
            ["keyname" => "RW", "textvalue" => "Rwanda"],
            ["keyname" => "ZM", "textvalue" => "Zambie"],
            ["keyname" => "TV", "textvalue" => "Tuvalu"],
            ["keyname" => "TZ", "textvalue" => "Tanzanie"],
            ["keyname" => "BI", "textvalue" => "Burundi"],
            ["keyname" => "AT", "textvalue" => "Autriche"],
            ["keyname" => "BB", "textvalue" => "Barbade"],
            ["keyname" => "GQ", "textvalue" => "Guinée équatoriale"],
            ["keyname" => "VI", "textvalue" => "Îles Vierges américaines"],
            ["keyname" => "PM", "textvalue" => "Saint-Pierre-et-Miquelon"],
            ["keyname" => "MD", "textvalue" => "Moldavie"],
            ["keyname" => "MH", "textvalue" => "Îles Marshall"],
            ["keyname" => "SE", "textvalue" => "Suède"],
            ["keyname" => "CD", "textvalue" => "République démocratique du Congo"],
            ["keyname" => "MX", "textvalue" => "Mexique"],
            ["keyname" => "GW", "textvalue" => "Guinée-Bissau"],
            ["keyname" => "NL", "textvalue" => "Pays-Bas"],
            ["keyname" => "CN", "textvalue" => "Chine"],
            ["keyname" => "DE", "textvalue" => "Allemagne"],
            ["keyname" => "CA", "textvalue" => "Canada"],
            ["keyname" => "BH", "textvalue" => "Bahreïn"],
            ["keyname" => "JE", "textvalue" => "Jersey"],
            ["keyname" => "HR", "textvalue" => "Croatie"],
            ["keyname" => "GY", "textvalue" => "Guyane"],
            ["keyname" => "BL", "textvalue" => "Saint-Barthélemy"],
            ["keyname" => "MG", "textvalue" => "Madagascar"],
            ["keyname" => "AW", "textvalue" => "Aruba"],
            ["keyname" => "GG", "textvalue" => "Guernesey"],
            ["keyname" => "VE", "textvalue" => "Venezuela"],
            ["keyname" => "MC", "textvalue" => "Monaco"],
            ["keyname" => "HN", "textvalue" => "Honduras"],
            ["keyname" => "BE", "textvalue" => "Belgique"],
            ["keyname" => "UY", "textvalue" => "Uruguay"],
            ["keyname" => "GH", "textvalue" => "Ghana"],
            ["keyname" => "ME", "textvalue" => "Monténégro"],
            ["keyname" => "CG", "textvalue" => "République du Congo"],
            ["keyname" => "LR", "textvalue" => "Libéria"],
            ["keyname" => "LA", "textvalue" => "Laos"],
            ["keyname" => "FR", "textvalue" => "France"],
            ["keyname" => "PL", "textvalue" => "Pologne"],
            ["keyname" => "NF", "textvalue" => "Île Norfolk"],
            ["keyname" => "TN", "textvalue" => "Tunisie"],
            ["keyname" => "MY", "textvalue" => "Malaisie"],
            ["keyname" => "GL", "textvalue" => "Groenland"],
            ["keyname" => "GE", "textvalue" => "Géorgie"],
            ["keyname" => "YE", "textvalue" => "Yémen"],
            ["keyname" => "SX", "textvalue" => "Saint-Martin (partie néerlandaise)"],
            ["keyname" => "DK", "textvalue" => "Danemark"],
            ["keyname" => "ET", "textvalue" => "Éthiopie"],
            ["keyname" => "YT", "textvalue" => "Mayotte"],
            ["keyname" => "GM", "textvalue" => "Gambie"],
            ["keyname" => "NE", "textvalue" => "Niger"],
            ["keyname" => "SJ", "textvalue" => "Svalbard et Jan Mayen"],
            ["keyname" => "RU", "textvalue" => "Russie"],
            ["keyname" => "FO", "textvalue" => "Îles Féroé"],
            ["keyname" => "BO", "textvalue" => "Bolivie"],
            ["keyname" => "TJ", "textvalue" => "Tadjikistan"],
            ["keyname" => "BD", "textvalue" => "Bangladesh"],
            ["keyname" => "NA", "textvalue" => "Namibie"],
            ["keyname" => "QA", "textvalue" => "Qatar"],
            ["keyname" => "ST", "textvalue" => "Sao Tomé-et-Principe"],
            ["keyname" => "KZ", "textvalue" => "Kazakhstan"],
            ["keyname" => "BV", "textvalue" => "Île Bouvet"],
            ["keyname" => "PW", "textvalue" => "Palau"],
            ["keyname" => "BY", "textvalue" => "Biélorussie"],
            ["keyname" => "AM", "textvalue" => "Arménie"],
            ["keyname" => "MA", "textvalue" => "Maroc"],
            ["keyname" => "BZ", "textvalue" => "Belize"],
            ["keyname" => "GF", "textvalue" => "Guyane française"],
            ["keyname" => "UA", "textvalue" => "Ukraine"],
            ["keyname" => "FK", "textvalue" => "Îles Falkland"],
            ["keyname" => "IQ", "textvalue" => "Irak"],
            ["keyname" => "NU", "textvalue" => "Nauru"],
            ["keyname" => "AI", "textvalue" => "Anguilla"],
            ["keyname" => "FI", "textvalue" => "Finlande"],
            ["keyname" => "MR", "textvalue" => "Mauritanie"],
            ["keyname" => "ER", "textvalue" => "Érythrée"],
            ["keyname" => "RE", "textvalue" => "Réunion"],
            ["keyname" => "GI", "textvalue" => "Gibraltar"],
            ["keyname" => "AQ", "textvalue" => "Antarctique"],
            ["keyname" => "FM", "textvalue" => "Micronésie"],
            ["keyname" => "GR", "textvalue" => "Grèce"],
            ["keyname" => "PH", "textvalue" => "Philippines"],
            ["keyname" => "LY", "textvalue" => "Libye"],
            ["keyname" => "UZ", "textvalue" => "Ouzbékistan"],
            ["keyname" => "IN", "textvalue" => "Inde"],
            ["keyname" => "BW", "textvalue" => "Botswana"],
            ["keyname" => "SZ", "textvalue" => "Eswatini"],
            ["keyname" => "RS", "textvalue" => "Serbie"],
            ["keyname" => "AU", "textvalue" => "Australie"],
            ["keyname" => "PN", "textvalue" => "Pitcairn"],
            ["keyname" => "AE", "textvalue" => "Émirats Arabes Unis"],
            ["keyname" => "KP", "textvalue" => "Corée du Nord"],
            ["keyname" => "ID", "textvalue" => "Indonésie"],
            ["keyname" => "SN", "textvalue" => "Sénégal"],
            ["keyname" => "IL", "textvalue" => "Israël"],
            ["keyname" => "VC", "textvalue" => "Saint-Vincent-et-les Grenadines"],
            ["keyname" => "PY", "textvalue" => "Paraguay"],
            ["keyname" => "CF", "textvalue" => "République centrafricaine"],
            ["keyname" => "GD", "textvalue" => "Grenade"],
            ["keyname" => "GS", "textvalue" => "Géorgie du Sud et les îles Sandwich du Sud"],
            ["keyname" => "VG", "textvalue" => "British Virgin Islands"],
            ["keyname" => "GP", "textvalue" => "Guadeloupe"],
            ["keyname" => "AX", "textvalue" => "Îles Åland"],
            ["keyname" => "OM", "textvalue" => "Oman"],
            ["keyname" => "AD", "textvalue" => "Andorre"],
            ["keyname" => "CI", "textvalue" => "Côte d’Ivoire"],
            ["keyname" => "MQ", "textvalue" => "Martinique"],
            ["keyname" => "MO", "textvalue" => "Macao"],
            ["keyname" => "NC", "textvalue" => "Nouvelle-Calédonie"],
            ["keyname" => "MT", "textvalue" => "Malte"],
            ["keyname" => "TR", "textvalue" => "Turquie"],
            ["keyname" => "SS", "textvalue" => "Sud-Soudan"],
            ["keyname" => "SH", "textvalue" => "Sainte-Hélène"],
            ["keyname" => "EE", "textvalue" => "Estonie"],
            ["keyname" => "LB", "textvalue" => "Liban"],
            ["keyname" => "KY", "textvalue" => "Iles Cayman"],
            ["keyname" => "CC", "textvalue" => "Îles Cocos"],
            ["keyname" => "EH", "textvalue" => "Sahara occidental"],
            ["keyname" => "MV", "textvalue" => "Maldives"],
            ["keyname" => "GU", "textvalue" => "Guam"],
            ["keyname" => "ZW", "textvalue" => "Zimbabwe"],
            ["keyname" => "WF", "textvalue" => "Wallis-et-Futuna"],
            ["keyname" => "TC", "textvalue" => "Îles Turques-et-Caïques"],
            ["keyname" => "JM", "textvalue" => "Jamaïque"],
            ["keyname" => "KR", "textvalue" => "Corée du Sud"],
            ["keyname" => "IM", "textvalue" => "Ile de Man"],
            ["keyname" => "MU", "textvalue" => "Maurice"],
            ["keyname" => "TK", "textvalue" => "Tokelau"],
            ["keyname" => "FJ", "textvalue" => "Fidji"],
            ["keyname" => "CM", "textvalue" => "Cameroun"],
            ["keyname" => "KE", "textvalue" => "Kenya"],
            ["keyname" => "PG", "textvalue" => "Papouasie-Nouvelle-Guinée"],
            ["keyname" => "LK", "textvalue" => "Sri Lanka"],
            ["keyname" => "VA", "textvalue" => "Saint-Siège (Vatican)"],
            ["keyname" => "KM", "textvalue" => "Comores"],
            ["keyname" => "BM", "textvalue" => "Bermudes"],
            ["keyname" => "NZ", "textvalue" => "Nouvelle-Zélande"],
            ["keyname" => "AZ", "textvalue" => "Azerbaïdjan"],
        ];

        return response()->json($countries);
    }
}
